load("//common:common_build_vars.bzl", "default_copts")

# cc_library(
#     name = "gamesvr_deps",
#     visibility = ["//visivility:public"],
#     deps = [

#     ],
# )

cc_binary(
    name = "chatsvr",
    srcs = glob(["**/*.h", "**/*.cpp"]),
    copts = default_copts,
    # deps = [
    #     "servers/gamesvr:gamesvr_deps",
    # ],
)