name: Black Format

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black
    - name: Get list of changed files
      id: changed-files
      run: |
        git fetch origin
        git diff --name-only origin/master...HEAD > changed_files.txt
    - name: Analysing the code with Black
      run: |
        if [ -s changed_files.txt ]; then
          cat changed_files.txt | grep '\.py$' | xargs black
        else
          echo "No Python files changed."
        fi
